import './globals.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="flex justify-center min-h-screen">
        <div className="w-[600px] shadow-xl min-h-screen p-6 mx-auto">
          <div className="font-bold text-xl mb-6">Pokemon Database</div>

          <div>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
